In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
with open("./alis/gzs/ali.post2") as ali_file:
    contents = ali_file.readlines()

In [3]:
with open("./alis/all_train.alignments") as ali_file2:
    contents2 = ali_file2.readlines()

In [4]:
line = contents[0]
labels_list = line.strip().split("[")
labels_list = [re.sub("\]", "", ele.strip()).strip().split()[0] for ele in labels_list]
speaker_id, sentence_id = labels_list[0].split("_")
alis_post = np.array([int(ele) for ele in labels_list[1:]])

In [5]:
ali_pdf = np.array([int(ele) for ele in contents2[1848].strip().split(" ")[1:]])

In [7]:
new_ali = alis_post - ali_pdf

In [8]:
non_zero_indices = []
for i in range(len(new_ali)):
    if(new_ali[i]):
        non_zero_indices.append(i)

In [12]:
non_zero_indices

[1,
 45,
 51,
 55,
 61,
 69,
 71,
 74,
 86,
 87,
 91,
 117,
 118,
 135,
 147,
 168,
 170,
 186,
 205,
 259,
 260,
 270,
 283,
 284,
 341,
 358,
 369,
 376,
 407,
 418,
 434,
 439,
 444,
 472]

In [16]:
print(ali_pdf[40:48])
print(alis_post[40:48])

[ 432   91   91   91  211  211 1547 1226]
[ 432   91   91   91  211 1547 1547 1226]


In [10]:
ali_pdf[non_zero_indices]

array([   0,  211,  663,  633,  263, 1836,   66, 1540, 1654, 1654, 1811,
        613,  613, 1880, 1220, 1899, 1774,  249,  566, 1226, 1666, 1301,
       1324,  900, 1384, 1812,  125,    2,  775, 1210,  867, 1282, 1630,
         49])

In [11]:
alis_post[non_zero_indices]

array([  54, 1547, 1226,  663,  633,   66, 1540,  450, 1630, 1630, 1200,
       1178, 1178, 1780, 1049, 1774,  530,  531,   78, 1373, 1226, 1864,
        900,  794, 1594, 1268,    0,   49,  632, 1359,  923,  288,  822,
         54])